const placeholderData = {
  location: "Seattle, WA",
  current: {
    temp: 68,
    condition: "Partly Cloudy",
    feelsLike: 65,
    high: 72,
    low: 58,
  },
  hourly: [
    { time: "3PM", temp: 68, condition: "Sunny" },
    { time: "4PM", temp: 69, condition: "Sunny" },
    { time: "5PM", temp: 69, condition: "Rainy" },
    { time: "6PM", temp: 65, condition: "Rainy" },
    { time: "7PM", temp: 64, condition: "Rainy" },
    { time: "8PM", temp: 63, condition: "Rainy" },
    { time: "9PM", temp: 62, condition: "Cloudy" },
    { time: "10PM", temp: 61, condition: "Cloudy" },
    { time: "11PM", temp: 60, condition: "Cloudy" },
    { time: "12AM", temp: 59, condition: "Cloudy" },
    { time: "1AM", temp: 58, condition: "Cloudy" },
    { time: "2AM", temp: 57, condition: "Cloudy" },
    { time: "3AM", temp: 56, condition: "Cloudy" },
    { time: "4AM", temp: 55, condition: "Cloudy" },
    { time: "5AM", temp: 54, condition: "Cloudy" },
    { time: "6AM", temp: 53, condition: "Cloudy" },
    { time: "7AM", temp: 52, condition: "Cloudy" },
    { time: "8AM", temp: 51, condition: "Cloudy" },
    { time: "9AM", temp: 50, condition: "Cloudy" },
  ],
  daily: [
    { day: "Mon", high: 72, low: 58, condition: "Cloudy" },
    { day: "Tue", high: 75, low: 60, condition: "Sunny" },
    { day: "Wed", high: 70, low: 55, condition: "Rainy" },
    { day: "Thu", high: 68, low: 54, condition: "Cloudy" },
    { day: "Fri", high: 71, low: 56, condition: "Sunny" },
    { day: "Sat", high: 73, low: 57, condition: "Sunny" },
    { day: "Sun", high: 69, low: 55, condition: "Rainy" },
    { day: "Mon", high: 72, low: 58, condition: "Cloudy" },
    { day: "Tue", high: 75, low: 60, condition: "Sunny" },
    { day: "Wed", high: 70, low: 55, condition: "Rainy" },
  ],
};

export default placeholderData;
